# Use the language closest to rust, as rust itself is not supported
language: c

notifications:
  email:
    on_success: never
    on_failure: always

before_install:
  - wget http://static.rust-lang.org/dist/rust-nightly-x86_64-unknown-linux-gnu.tar.gz
install:
  - sudo apt-get install libsdl1.2-dev libsdl-mixer1.2-dev libsdl-image1.2-dev
  - tar -xf rust-nightly-x86_64-unknown-linux-gnu.tar.gz
  - export RUSTC=$(pwd)/rust-nightly-x86_64-unknown-linux-gnu/bin/rustc
script:
  - $RUSTC -v
  - make
  - make test
