language: rust

rust:
  - stable

sudo: false

notifications:
  email:
    on_success: never
    on_failure: always

addons:
    apt:
        sources:
            - debian-sid
        packages:
            - libsdl2-dev

script:
  - make debug
  - make test
