language: rust

notifications:
  email:
    on_success: never
    on_failure: always

install:
  - wget http://www.libsdl.org/release/SDL2-2.0.3.tar.gz
  - tar -zxvf SDL2-2.0.3.tar.gz
  - cd SDL2-2.0.3
  - ./configure && make && sudo make install
  - cd -
script:
  - make
  - make opt
  - make test
