language: rust

notifications:
  email:
    on_success: never
    on_failure: always

install:
  - sudo apt-get update
  - sudo apt-get install libsdl2-dev
script:
  - make
  - make opt
  - make test
