language: rust

notifications:
  email:
    on_success: never
    on_failure: always

install:
  - yes | sudo add-apt-repository ppa:zoogie/sdl2-snapshots
  - sudo apt-get update
  - sudo apt-get install libsdl2
script:
  - make
  - make opt
  - make test
