# Use the language closest to rust, as rust itself is not supported
language: c

notifications:
  email:
    on_success: never
    on_failure: always

install:
  - sudo apt-get install libsdl1.2-dev
  - curl https://static.rust-lang.org/rustup.sh | sudo sh -
script:
  - make
  - make test
  - make opt
