language: rust

rust:
  - 1.0.0-beta
  - nightly

notifications:
  email:
    on_success: never
    on_failure: always

sudo: required

install:
  - sudo add-apt-repository ppa:team-xbmc/ppa -y
  - sudo apt-get update -q
  - sudo apt-get install libsdl2-dev

script:
  - make debug
  - make test
