[package]
name = "rboy"
version = "0.1.0"
authors = [ "mvdnes <git@mathijs.vd-nes.nl>" ]

[lib]
name = "rboy"

[dependencies]
time = "0.1"
podio = "0.1"

[dependencies.sdl2]
git = "https://github.com/AngryLawyer/rust-sdl2.git"

[features]
use-pkgconfig = [ "sdl2/use-pkgconfig" ]

[[bin]]
name = "rboy"
test = false
doc = false
