[package]

name = "rboy"
version = "0.1.0"
authors = [ "mvdnes <git@mathijs.vd-nes.nl>" ]

[lib]

name = "rboy"

[dependencies.sdl]
git = "https://github.com/brson/rust-sdl.git"

[[bin]]
name = "rboy"
test = false
doc = false
