[package]
name = "rboy"
version = "0.1.0"
authors = [ "mvdnes <git@mathijs.vd-nes.nl>" ]

[dependencies]
time = "0.1"
podio = "0.1"
glium = { version = "0.13", default_features = false, features = [ "glutin" ] }
clap = { version = "1", default_features = false }
blip_buf = ">=0.1.3"
cpal = "0.2"

[[bin]]
name = "rboy"
test = false
doc = false
