[package]
name = "rboy"
version = "0.1.0"
authors = [ "mvdnes <git@mathijs.vd-nes.nl>" ]

[lib]
name = "rboy"

[dependencies]
sdl2 = "*"
chrono = "0.2"
log = "*"
getopts = "*"
podio = "^0.0"

[features]
use-pkgconfig = [ "sdl2/use-pkgconfig" ]

[[bin]]
name = "rboy"
test = false
doc = false
