[package]
name = "rboy"
version = "0.1.0"
authors = [ "mvdnes <git@mathijs.vd-nes.nl>" ]
edition = "2018"

[dependencies]
blip_buf = ">=0.1.3"
clap = { version = "4", default_features = false, features = [ "std" ] }
cpal = "0.13"
glium = { version = "0.31", default_features = false, features = [ "glutin" ] }

[[bin]]
name = "rboy"
test = false
doc = false
