[package]
name = "rboy"
version = "0.1.0"
authors = [ "mvdnes <git@mathijs.vd-nes.nl>" ]

[lib]
name = "rboy"

[dependencies.sdl2]
git = "https://github.com/mvdnes/rust-sdl2.git"
branch = "sys"

[dependencies.time]
git = "http://github.com/rust-lang/time"

[dependencies.log]
git = "https://github.com/rust-lang/log"

[profile.test]
opt-level = 3
debug = true

[[bin]]
name = "rboy"
test = false
doc = false
