[package]
name = "rboy"
version = "0.1.0"
authors = [ "mvdnes <git@mathijs.vd-nes.nl>" ]

[dependencies]
time = "0.1"
podio = "0.1"
sdl2 = "0.9"

[features]
use-pkgconfig = [ "sdl2/use-pkgconfig" ]

[[bin]]
name = "rboy"
test = false
doc = false
