[package]
name = "rboy"
version = "0.1.0"
authors = [ "mvdnes <git@mathijs.vd-nes.nl>" ]

[dependencies]
time = "0.1"
podio = "0.1"
glium = { version = "0.10", default_features = false, features = [ "glutin" ] }
clap = { version = "1.4", default_features = false }

[[bin]]
name = "rboy"
test = false
doc = false
